# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: data-function-app
metadata:
  template: python-function-app@0.0.1-beta

# Provision Azure resources
infra:
  provider: bicep
  path: infra

# Deploy application code
services:
  datafunction:
    project: ./function_app
    language: python
    host: function

# Continuous integration
pipeline:
  provider: github
